// const data = () => {
const type = {
    Grass: "Grass",
    Poison: "Poison",
    Fire: "Fire",
    Flying: "Flying",
    Water: "Water",
    Bug: "Bug",
    Poison: "Poison",
    Normal: "Normal",
    Ground: "Ground",
    Ice: "Ice",
    Dragon: "Dragon",
    Electric: "Electric",
    Fairy: "Fairy",
    Steel: "Steel",
};

export const pokemons = [
    {
        id: 1,
        name: "Bulbasaur",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 2,
        name: "Ivysaur",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/ivysaur.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 3,
        name: "Venusaur",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/venusaur.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 4,
        name: "Charmander",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/charmander.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 5,
        name: "Charmeleon",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/charmeleon.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 6,
        name: "Charizard",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/charizard.jpg",
        pokemonTypes: [type.Fire, type.Flying],
    },
    {
        id: 7,
        name: "Squirtle",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/squirtle.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 8,
        name: "Wartortle",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/wartortle.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 9,
        name: "Blastoise",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/blastoise.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 10,
        name: "Caterpie",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/caterpie.jpg",
        pokemonTypes: [type.Bug],
    },
    {
        id: 11,
        name: "Metapod",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/metapod.jpg",
        pokemonTypes: [type.Bug],
    },
    {
        id: 12,
        name: "Butterfree",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/butterfree.jpg",
        pokemonTypes: [type.Bug, type.Flying],
    },
    {
        id: 13,
        name: "Weedle",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/weedle.jpg",
        pokemonTypes: [type.Bug, type.Poison],
    },
    {
        id: 14,
        name: "Kakuna",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/kakuna.jpg",
        pokemonTypes: [type.Bug, type.Poison],
    },
    {
        id: 15,
        name: "Beedrill",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/beedrill.jpg",
        pokemonTypes: [type.Bug, type.Poison],
    },
    {
        id: 16,
        name: "Pidgey",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/pidgey.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 17,
        name: "Pidgeotto",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/pidgeotto.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 18,
        name: "Pidgeot",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/pidgeot.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 19,
        name: "Rattata",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/rattata.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 20,
        name: "Raticate",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/raticate.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 21,
        name: "Spearow",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/spearow.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 22,
        name: "Fearow",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/fearow.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 23,
        name: "Ekans",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/ekans.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 24,
        name: "Arbok",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/arbok.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 25,
        name: "Pikachu",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/pikachu.jpg",
        pokemonTypes: [type.Electric],
    },
    {
        id: 26,
        name: "Raichu",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/raichu.jpg",
        pokemonTypes: [type.Electric],
    },
    {
        id: 27,
        name: "Sandshrew",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/sandshrew.jpg",
        pokemonTypes: [type.Ground],
    },
    {
        id: 28,
        name: "Sandslash",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/sandslash.jpg",
        pokemonTypes: [type.Ground],
    },
    {
        id: 29,
        name: "Nidoran♀",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/nidoran-f.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 30,
        name: "Nidorina",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/nidorina.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 31,
        name: "Nidoqueen",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/nidoqueen.jpg",
        pokemonTypes: [type.Poison, type.Ground],
    },
    {
        id: 32,
        name: "Nidoran♂",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/nidoran-m.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 33,
        name: "Nidorino",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/nidorino.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 34,
        name: "Nidoking",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/nidoking.jpg",
        pokemonTypes: [type.Poison, type.Ground],
    },
    {
        id: 35,
        name: "Clefairy",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/clefairy.jpg",
        pokemonTypes: [type.Fairy],
    },
    {
        id: 36,
        name: "Clefable",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/clefable.jpg",
        pokemonTypes: [type.Fairy],
    },
    {
        id: 37,
        name: "Vulpix",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/vulpix.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 38,
        name: "Ninetales",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/ninetales.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 39,
        name: "Jigglypuff",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/jigglypuff.jpg",
        pokemonTypes: [type.Normal, type.Fairy],
    },
    {
        id: 40,
        name: "Wigglytuff",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/wigglytuff.jpg",
        pokemonTypes: [type.Normal, type.Fairy],
    },
    {
        id: 41,
        name: "Zubat",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/zubat.jpg",
        pokemonTypes: [type.Poison, type.Flying],
    },
    {
        id: 42,
        name: "Golbat",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/golbat.jpg",
        pokemonTypes: [type.Poison, type.Flying],
    },
    {
        id: 43,
        name: "Oddish",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/oddish.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 44,
        name: "Gloom",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/gloom.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 45,
        name: "Vileplume",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/vileplume.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 46,
        name: "Paras",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/paras.jpg",
        pokemonTypes: [type.Bug, type.Grass],
    },
    {
        id: 47,
        name: "Parasect",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/parasect.jpg",
        pokemonTypes: [type.Bug, type.Grass],
    },
    {
        id: 48,
        name: "Venonat",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/venonat.jpg",
        pokemonTypes: [type.Bug, type.Poison],
    },
    {
        id: 49,
        name: "Venomoth",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/venomoth.jpg",
        pokemonTypes: [type.Bug, type.Poison],
    },
    {
        id: 50,
        name: "Diglett",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/diglett.jpg",
        pokemonTypes: [type.Ground],
    },
    {
        id: 51,
        name: "Dugtrio",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/dugtrio.jpg",
        pokemonTypes: [type.Ground],
    },
    {
        id: 52,
        name: "Meowth",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/meowth.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 53,
        name: "Persian",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/persian.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 54,
        name: "Psyduck",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/psyduck.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 55,
        name: "Golduck",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/golduck.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 56,
        name: "Mankey",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/mankey.jpg",
        pokemonTypes: [type.Fighting],
    },
    {
        id: 57,
        name: "Primeape",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/primeape.jpg",
        pokemonTypes: [type.Fighting],
    },
    {
        id: 58,
        name: "Growlithe",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/growlithe.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 59,
        name: "Arcanine",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/arcanine.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 60,
        name: "Poliwag",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/poliwag.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 61,
        name: "Poliwhirl",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/poliwhirl.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 62,
        name: "Poliwrath",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/poliwrath.jpg",
        pokemonTypes: [type.Water, type.Fighting],
    },
    {
        id: 63,
        name: "Abra",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/abra.jpg",
        pokemonTypes: [type.Psychic],
    },
    {
        id: 64,
        name: "Kadabra",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/kadabra.jpg",
        pokemonTypes: [type.Psychic],
    },
    {
        id: 65,
        name: "Alakazam",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/alakazam.jpg",
        pokemonTypes: [type.Psychic],
    },
    {
        id: 66,
        name: "Machop",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/machop.jpg",
        pokemonTypes: [type.Fighting],
    },
    {
        id: 67,
        name: "Machoke",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/machoke.jpg",
        pokemonTypes: [type.Fighting],
    },
    {
        id: 68,
        name: "Machamp",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/machamp.jpg",
        pokemonTypes: [type.Fighting],
    },
    {
        id: 69,
        name: "Bellsprout",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/bellsprout.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 70,
        name: "Weepinbell",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/weepinbell.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 71,
        name: "Victreebel",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/victreebel.jpg",
        pokemonTypes: [type.Grass, type.Poison],
    },
    {
        id: 72,
        name: "Tentacool",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/tentacool.jpg",
        pokemonTypes: [type.Water, type.Poison],
    },
    {
        id: 73,
        name: "Tentacruel",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/tentacruel.jpg",
        pokemonTypes: [type.Water, type.Poison],
    },
    {
        id: 74,
        name: "Geodude",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/geodude.jpg",
        pokemonTypes: [type.Rock, type.Ground],
    },
    {
        id: 75,
        name: "Graveler",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/graveler.jpg",
        pokemonTypes: [type.Rock, type.Ground],
    },
    {
        id: 76,
        name: "Golem",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/golem.jpg",
        pokemonTypes: [type.Rock, type.Ground],
    },
    {
        id: 77,
        name: "Ponyta",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/ponyta.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 78,
        name: "Rapidash",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/rapidash.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 79,
        name: "Slowpoke",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/slowpoke.jpg",
        pokemonTypes: [type.Water, type.Psychic],
    },
    {
        id: 80,
        name: "Slowbro",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/slowbro.jpg",
        pokemonTypes: [type.Water, type.Psychic],
    },
    {
        id: 81,
        name: "Magnemite",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/magnemite.jpg",
        pokemonTypes: [type.Electric, type.Steel],
    },
    {
        id: 82,
        name: "Magneton",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/magneton.jpg",
        pokemonTypes: [type.Electric, type.Steel],
    },
    {
        id: 83,
        name: "Farfetch'd",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/farfetchd.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 84,
        name: "Doduo",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/doduo.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 85,
        name: "Dodrio",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/dodrio.jpg",
        pokemonTypes: [type.Normal, type.Flying],
    },
    {
        id: 86,
        name: "Seel",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/seel.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 87,
        name: "Dewgong",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/dewgong.jpg",
        pokemonTypes: [type.Water, type.Ice],
    },
    {
        id: 88,
        name: "Grimer",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/grimer.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 89,
        name: "Muk",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/muk.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 90,
        name: "Shellder",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/shellder.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 91,
        name: "Cloyster",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/cloyster.jpg",
        pokemonTypes: [type.Water, type.Ice],
    },
    {
        id: 92,
        name: "Gastly",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/gastly.jpg",
        pokemonTypes: [type.Ghost, type.Poison],
    },
    {
        id: 93,
        name: "Haunter",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/haunter.jpg",
        pokemonTypes: [type.Ghost, type.Poison],
    },
    {
        id: 94,
        name: "Gengar",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/gengar.jpg",
        pokemonTypes: [type.Ghost, type.Poison],
    },
    {
        id: 95,
        name: "Onix",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/onix.jpg",
        pokemonTypes: [type.Rock, type.Ground],
    },
    {
        id: 96,
        name: "Drowzee",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/drowzee.jpg",
        pokemonTypes: [type.Psychic],
    },
    {
        id: 97,
        name: "Hypno",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/hypno.jpg",
        pokemonTypes: [type.Psychic],
    },
    {
        id: 98,
        name: "Krabby",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/krabby.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 99,
        name: "Kingler",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/kingler.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 100,
        name: "Voltorb",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/voltorb.jpg",
        pokemonTypes: [type.Electric],
    },
    {
        id: 101,
        name: "Electrode",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/electrode.jpg",
        pokemonTypes: [type.Electric],
    },
    {
        id: 102,
        name: "Exeggcute",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/exeggcute.jpg",
        pokemonTypes: [type.Grass, type.Psychic],
    },
    {
        id: 103,
        name: "Exeggutor",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/exeggutor.jpg",
        pokemonTypes: [type.Grass, type.Psychic],
    },
    {
        id: 104,
        name: "Cubone",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/cubone.jpg",
        pokemonTypes: [type.Ground],
    },
    {
        id: 105,
        name: "Marowak",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/marowak.jpg",
        pokemonTypes: [type.Ground],
    },
    {
        id: 106,
        name: "Hitmonlee",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/hitmonlee.jpg",
        pokemonTypes: [type.Fighting],
    },
    {
        id: 107,
        name: "Hitmonchan",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/hitmonchan.jpg",
        pokemonTypes: [type.Fighting],
    },
    {
        id: 108,
        name: "Lickitung",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/lickitung.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 109,
        name: "Koffing",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/koffing.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 110,
        name: "Weezing",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/weezing.jpg",
        pokemonTypes: [type.Poison],
    },
    {
        id: 111,
        name: "Rhyhorn",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/rhyhorn.jpg",
        pokemonTypes: [type.Ground, type.Rock],
    },
    {
        id: 112,
        name: "Rhydon",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/rhydon.jpg",
        pokemonTypes: [type.Ground, type.Rock],
    },
    {
        id: 113,
        name: "Chansey",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/chansey.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 114,
        name: "Tangela",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/tangela.jpg",
        pokemonTypes: [type.Grass],
    },
    {
        id: 115,
        name: "Kangaskhan",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/kangaskhan.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 116,
        name: "Horsea",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/horsea.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 117,
        name: "Seadra",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/seadra.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 118,
        name: "Goldeen",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/goldeen.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 119,
        name: "Seaking",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/seaking.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 120,
        name: "Staryu",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/staryu.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 121,
        name: "Starmie",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/starmie.jpg",
        pokemonTypes: [type.Water, type.Psychic],
    },
    {
        id: 122,
        name: "Mr. Mime",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/mr-mime.jpg",
        pokemonTypes: [type.Psychic, type.Fairy],
    },
    {
        id: 123,
        name: "Scyther",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/scyther.jpg",
        pokemonTypes: [type.Bug, type.Flying],
    },
    {
        id: 124,
        name: "Jynx",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/jynx.jpg",
        pokemonTypes: [type.Ice, type.Psychic],
    },
    {
        id: 125,
        name: "Electabuzz",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/electabuzz.jpg",
        pokemonTypes: [type.Electric],
    },
    {
        id: 126,
        name: "Magmar",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/magmar.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 127,
        name: "Pinsir",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/pinsir.jpg",
        pokemonTypes: [type.Bug],
    },
    {
        id: 128,
        name: "Tauros",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/tauros.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 129,
        name: "Magikarp",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/magikarp.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 130,
        name: "Gyarados",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/gyarados.jpg",
        pokemonTypes: [type.Water, type.Flying],
    },
    {
        id: 131,
        name: "Lapras",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/lapras.jpg",
        pokemonTypes: [type.Water, type.Ice],
    },
    {
        id: 132,
        name: "Ditto",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/ditto.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 133,
        name: "Eevee",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/eevee.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 134,
        name: "Vaporeon",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/vaporeon.jpg",
        pokemonTypes: [type.Water],
    },
    {
        id: 135,
        name: "Jolteon",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/jolteon.jpg",
        pokemonTypes: [type.Electric],
    },
    {
        id: 136,
        name: "Flareon",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/flareon.jpg",
        pokemonTypes: [type.Fire],
    },
    {
        id: 137,
        name: "Porygon",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/porygon.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 138,
        name: "Omanyte",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/omanyte.jpg",
        pokemonTypes: [type.Rock, type.Water],
    },
    {
        id: 139,
        name: "Omastar",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/omastar.jpg",
        pokemonTypes: [type.Rock, type.Water],
    },
    {
        id: 140,
        name: "Kabuto",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/kabuto.jpg",
        pokemonTypes: [type.Rock, type.Water],
    },
    {
        id: 141,
        name: "Kabutops",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/kabutops.jpg",
        pokemonTypes: [type.Rock, type.Water],
    },
    {
        id: 142,
        name: "Aerodactyl",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/aerodactyl.jpg",
        pokemonTypes: [type.Rock, type.Flying],
    },
    {
        id: 143,
        name: "Snorlax",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/snorlax.jpg",
        pokemonTypes: [type.Normal],
    },
    {
        id: 144,
        name: "Articuno",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/articuno.jpg",
        pokemonTypes: [type.Ice, type.Flying],
    },
    {
        id: 145,
        name: "Zapdos",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/zapdos.jpg",
        pokemonTypes: [type.Electric, type.Flying],
    },
    {
        id: 146,
        name: "Moltres",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/moltres.jpg",
        pokemonTypes: [type.Fire, type.Flying],
    },
    {
        id: 147,
        name: "Dratini",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/dratini.jpg",
        pokemonTypes: [type.Dragon],
    },
    {
        id: 148,
        name: "Dragonair",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/dragonair.jpg",
        pokemonTypes: [type.Dragon],
    },
    {
        id: 149,
        name: "Dragonite",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/dragonite.jpg",
        pokemonTypes: [type.Dragon, type.Flying],
    },
    {
        id: 150,
        name: "Mewtwo",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/mewtwo.jpg",
        pokemonTypes: [type.Psychic],
    },
    {
        id: 151,
        name: "Mew",
        captured: false,
        imgUrl: "http://img.pokemondb.net/artwork/mew.jpg",
        pokemonTypes: [type.Psychic],
    },
];
